Repository UMC-Master/frontend, pull requests merged in 2025-02, with the labels that each got.

#50 Feat/#43 UI save tip page
  umc-master/src/components/Card/Card.tsx
  umc-master/src/components/Skeleton/SkeletonCard.tsx
  umc-master/src/pages/mypage/components/RecentTips.tsx
  umc-master/src/pages/saveTip/SaveTipPage.tsx
  umc-master/src/pages/saveTip/dummydata/dummydata.ts
  umc-master/src/pages/saveTip/dummydata/image.png
Labels: ✨feature, 🎨 UI

#56 Feat/#54 feat quiz modify and on click add
  umc-master/src/components/Card/BigCard.tsx
  umc-master/src/pages/createPost/CreatePostPage.tsx
  umc-master/src/pages/main/components/QuizBox.tsx
  umc-master/src/pages/search/components/RecommendTipsSection.tsx
Labels: ✨feature, 🎨 UI

#51 Feat/#36 UI magazine
  umc-master/src/components/Card/Card.tsx
  umc-master/src/components/Card/CardInfo.tsx
  umc-master/src/pages/magazine/MagazineDetailPage.tsx
  umc-master/src/pages/magazine/MagazinePage.tsx
  umc-master/src/pages/magazine/components/cardGrid.tsx
  umc-master/src/pages/magazine/components/mindMap.tsx
  umc-master/yarn.lock
Labels: 🎨 UI

#57 Feat/#52 랜딩페이지, 네비게이션 모달창 UI
  umc-master/src/assets/character/landing.png
  umc-master/src/assets/icons/logout.svg
  umc-master/src/assets/icons/tip.svg
  umc-master/src/assets/icons/user.svg
  umc-master/src/assets/logo.png
  umc-master/src/components/Modal/profile.tsx
  umc-master/src/components/NavigationBar/NavigationBar.tsx
  umc-master/src/components/common/typography.ts
  umc-master/src/pages/landing/components/InfluencerSection.tsx
  umc-master/src/pages/landing/components/SavedTipsSection.tsx
  umc-master/src/pages/landing/components/SectionScrollIndicator.tsx
  umc-master/src/pages/landing/components/StartButton.tsx
  umc-master/src/pages/landing/components/TipsSection.tsx
  umc-master/src/pages/landing/components/TitleSection.tsx
Labels: 🎨 UI

#58 Feat/#44 UI save tip detail page
  umc-master/src/assets/savetipdetail/Likes.svg
  umc-master/src/assets/savetipdetail/liked.svg
  umc-master/src/assets/savetipdetail/link.svg
  umc-master/src/assets/savetipdetail/saved.svg
  umc-master/src/assets/savetipdetail/saves.svg
  umc-master/src/components/Skeleton/SkeletonComment.tsx
  umc-master/src/pages/saveTip/DetailPage_componenets/CommentView.tsx
  umc-master/src/pages/saveTip/DetailPage_componenets/PostDetail.tsx
  umc-master/src/pages/saveTip/SaveTipDetailPage.tsx
  umc-master/src/pages/saveTip/SaveTipPage.tsx
  umc-master/src/pages/saveTip/dummydata/dummydata.ts
Labels: 🎨 UI

#61 Fix/#59 fix search page modify
  umc-master/src/pages/main/components/TipsSection.tsx
  umc-master/src/pages/search/components/RecommendTipsSection.tsx
Labels: :hammer: Fix

#67 Feat/#49 feature login
  umc-master/src/apis/profileApi.ts
  umc-master/src/components/Modal/profile.tsx
  umc-master/src/layouts/root-layout.tsx
  umc-master/src/pages/auth/FindPrivacy.tsx
  umc-master/src/pages/auth/KakaoCallback.tsx
  umc-master/src/pages/auth/Login_components/InputForm.tsx
  umc-master/src/router/routePaths.ts
  umc-master/src/router/routes.tsx
  umc-master/src/store/authStore.ts
  umc-master/src/store/userStore.ts
Labels: ✨feature

#70 [DEPLOY] 2차 배포
  umc-master/src/apis/profileApi.ts
  umc-master/src/components/Modal/profile.tsx
  umc-master/src/layouts/root-layout.tsx
  umc-master/src/pages/auth/FindPrivacy.tsx
  umc-master/src/pages/auth/KakaoCallback.tsx
  umc-master/src/pages/auth/Login_components/InputForm.tsx
  umc-master/src/router/routePaths.ts
  umc-master/src/router/routes.tsx
  umc-master/src/store/authStore.ts
  umc-master/src/store/userStore.ts
Labels: 🚀 deploy

#68 Feat/#64 feat main page modify
  umc-master/src/apis/axios-instance.ts
  umc-master/src/apis/queries/useQuizMutations.ts
  umc-master/src/apis/queries/useQuizQueries.ts
  umc-master/src/apis/queries/useSearchList.ts
  umc-master/src/apis/quizApi.ts
  umc-master/src/apis/searchApi.ts
  umc-master/src/assets/dummy/dummyData.ts
  umc-master/src/components/NavigationBar/NavigationBar.tsx
  umc-master/src/pages/createPost/CreatePostPage.tsx
  umc-master/src/pages/main/components/Banner.tsx
  umc-master/src/pages/main/components/Categories.tsx
  umc-master/src/pages/main/components/QuizBox.tsx
  umc-master/src/pages/main/components/TipsSection.tsx
  umc-master/src/pages/search/SearchPage.tsx
  umc-master/src/store/tokenStore.ts
Labels: ✨feature, ♻ refactor

#74 Feat/#73 feat create page modify
  umc-master/src/apis/queries/useTipMutations.ts
  umc-master/src/apis/tipApi.ts
  umc-master/src/components/Modal/search.tsx
  umc-master/src/pages/createPost/CreatePostPage.tsx
Labels: ✨feature, 🌐 api

#80 Feat/#79 feat image upload & ErrorPage & SearchTag
  umc-master/src/apis/queries/useSearchList.ts
  umc-master/src/apis/searchApi.ts
  umc-master/src/apis/tipApi.ts
  umc-master/src/assets/error.svg
  umc-master/src/components/Modal/search.tsx
  umc-master/src/pages/createPost/CreatePostPage.tsx
  umc-master/src/pages/createPost/components/ImageUpload.tsx
  umc-master/src/pages/error/ErrorPage.tsx
  umc-master/src/pages/main/components/TipsSection.tsx
  umc-master/src/pages/search/SearchPage.tsx
  umc-master/src/router/routes.tsx
Labels: ✨feature, 🎨 UI

#81 Feat/#60 UI chatbot
  umc-master/src/apis/chatApi.ts
  umc-master/src/apis/queries/useChatMutations.ts
  umc-master/src/assets/icons/chatbot.svg
  umc-master/src/assets/icons/right_arrow.svg
  umc-master/src/assets/icons/send.svg
  umc-master/src/pages/chat/ChatPage.tsx
  umc-master/src/pages/chat/components/ButtonList.tsx
  umc-master/src/pages/chat/components/SearchInput.tsx
  umc-master/src/pages/chat/components/Sidebar.tsx
  umc-master/src/router/routePaths.ts
  umc-master/src/router/routes.tsx
Labels: ✨feature, 🌐 api, 🎨 UI

#86 [DEVELOP] 3차 배포
  umc-master/src/apis/axios-instance.ts
  umc-master/src/apis/chatApi.ts
  umc-master/src/apis/queries/useChatMutations.ts
  umc-master/src/apis/queries/useQuizMutations.ts
  umc-master/src/apis/queries/useQuizQueries.ts
  umc-master/src/apis/queries/useSearchList.ts
  umc-master/src/apis/queries/useTipMutations.ts
  umc-master/src/apis/quizApi.ts
  umc-master/src/apis/searchApi.ts
  umc-master/src/apis/tipApi.ts
  umc-master/src/assets/dummy/dummyData.ts
  umc-master/src/assets/dummyImage/clean.png
  umc-master/src/assets/error.svg
  umc-master/src/assets/icons/chatbot.svg
  umc-master/src/assets/icons/person.svg
  umc-master/src/assets/icons/right_arrow.svg
  umc-master/src/assets/icons/send.svg
  umc-master/src/assets/mainCharacter2.png
  umc-master/src/components/Card/Card.tsx
  umc-master/src/components/Card/NumberCard.tsx
  umc-master/src/components/Modal/search.tsx
  umc-master/src/components/NavigationBar/NavigationBar.tsx
  umc-master/src/pages/challenge/ChallengePage.tsx
  umc-master/src/pages/challenge/compoents/Banner.tsx
  umc-master/src/pages/challenge/compoents/ChallengeHeader.tsx
  umc-master/src/pages/challenge/compoents/TipSection.tsx
  umc-master/src/pages/chat/ChatPage.tsx
  umc-master/src/pages/chat/components/ButtonList.tsx
  umc-master/src/pages/chat/components/SearchInput.tsx
  umc-master/src/pages/chat/components/Sidebar.tsx
  umc-master/src/pages/createPost/CreatePostPage.tsx
  umc-master/src/pages/createPost/components/ImageUpload.tsx
  umc-master/src/pages/error/ErrorPage.tsx
  umc-master/src/pages/main/components/Banner.tsx
  umc-master/src/pages/main/components/Categories.tsx
  umc-master/src/pages/main/components/QuizBox.tsx
  umc-master/src/pages/main/components/TipsSection.tsx
  umc-master/src/pages/search/SearchPage.tsx
  umc-master/src/router/routePaths.ts
  umc-master/src/router/routes.tsx
  umc-master/src/store/tokenStore.ts
Labels: 🚀 deploy

#87 Feat/#85 feat main page filter & chatbot Icon
  umc-master/src/apis/queries/useSearchList.ts
  umc-master/src/apis/searchApi.ts
  umc-master/src/pages/main/MainPage.tsx
  umc-master/src/pages/main/components/Categories.tsx
  umc-master/src/pages/main/components/TipsSection.tsx
  umc-master/src/pages/search/SearchPage.tsx
  umc-master/src/pages/search/components/RecommendTipsSection.tsx
  umc-master/src/pages/search/components/RecommendTitle.tsx
  umc-master/src/store/userStore.ts
Labels: ✨feature, 🌐 api, ♻ refactor

#93 Feat/#89 Navigation bar UI
  umc-master/index.html
  umc-master/public/favicon.svg
  umc-master/src/components/NavigationBar/NavigationBar.tsx
Labels: ✨feature, 🎨 UI

#98 Fix/#96 fix landing page access
  umc-master/src/apis/axios-instance.ts
  umc-master/src/components/Auth/AuthWrapper.tsx
  umc-master/src/router/routes.tsx
  umc-master/src/store/tokenStore.ts
Labels: ✨feature, :hammer: Fix

#99 Feat/#66 fix signup modify
  umc-master/src/apis/authApi.ts
  umc-master/src/pages/auth/SignUpPage.tsx
  umc-master/src/pages/auth/Signup_components/AgreementForm.tsx
  umc-master/src/pages/auth/Signup_components/EmailForm.tsx
  umc-master/src/pages/auth/Signup_components/PasswordForm.tsx
  umc-master/src/pages/auth/Signup_components/PrivacyForm.tsx
  umc-master/src/pages/auth/Signup_components/SignupState.tsx
Labels: ✨feature, 🌐 api

#100 Fix/#97/saved tips
  umc-master/src/components/Modal/profile.tsx
  umc-master/src/components/NavigationBar/NavigationBar.tsx
  umc-master/src/pages/community/components/Banner.tsx
  umc-master/src/pages/saveTip/SaveTipPage.tsx
  umc-master/src/pages/saveTip/components/PostDetail.tsx
Labels: 🐞 bug, :hammer: Fix

#101 [DEPLOY] 5차 배포
  umc-master/src/apis/authApi.ts
  umc-master/src/apis/axios-instance.ts
  umc-master/src/components/Auth/AuthWrapper.tsx
  umc-master/src/components/Modal/profile.tsx
  umc-master/src/components/NavigationBar/NavigationBar.tsx
  umc-master/src/pages/auth/SignUpPage.tsx
  umc-master/src/pages/auth/Signup_components/AgreementForm.tsx
  umc-master/src/pages/auth/Signup_components/EmailForm.tsx
  umc-master/src/pages/auth/Signup_components/PasswordForm.tsx
  umc-master/src/pages/auth/Signup_components/PrivacyForm.tsx
  umc-master/src/pages/auth/Signup_components/SignupState.tsx
  umc-master/src/pages/community/components/Banner.tsx
  umc-master/src/pages/saveTip/SaveTipPage.tsx
  umc-master/src/pages/saveTip/components/PostDetail.tsx
  umc-master/src/router/routes.tsx
  umc-master/src/store/tokenStore.ts
Labels: 🚀 deploy

#102 Feat/#69 feature kakao login
  umc-master/index.html
  umc-master/src/pages/auth/KakaoCallback.tsx
  umc-master/src/pages/auth/Login_components/InputForm.tsx
Labels: ✨feature

#105 Feat/#104 fix demo modify
  umc-master/src/pages/main/components/TipsSection.tsx
  umc-master/src/pages/mypage/components/RecentTips.tsx
Labels: ✨feature, :hammer: Fix
