Repository UMC-Master/frontend, pull requests merged in 2025-01, with the labels that each got.

#5 Chore/#4 page routing
  umc-master/src/App.tsx
  umc-master/src/router/routes.tsx
Labels: ⚙ chore

#6 [CHORE] 페이지 라우팅, 절대 경로
  umc-master/.eslintrc.json
  umc-master/.prettierrc
  umc-master/eslint.config.js
  umc-master/package.json
  umc-master/src/App.tsx
  umc-master/src/index.css
  umc-master/src/pages/auth/LoginPage.tsx
  umc-master/src/pages/auth/SignUpPage.tsx
  umc-master/src/pages/community/CommunityPage.tsx
  umc-master/src/pages/createPost/CreatePostPage.tsx
  umc-master/src/pages/landing/LandingPage.tsx
  umc-master/src/pages/magazine/MagazineDetailPage.tsx
  umc-master/src/pages/magazine/MagazinePage.tsx
  umc-master/src/pages/main/MainPage.tsx
  umc-master/src/pages/saveTip/SaveTipDetailPage.tsx
  umc-master/src/pages/saveTip/SaveTipPage.tsx
  umc-master/src/pages/search/SearchPage.tsx
  umc-master/src/router/routePaths.ts
  umc-master/src/router/routes.tsx
  umc-master/tsconfig.app.json
  umc-master/vite.config.ts
  umc-master/yarn.lock
Labels: ⚙ chore

#13 Feat/#11 UI mainpage
  .github/workflows/preview.yml
  umc-master/package.json
  umc-master/src/components/Card/Card.tsx
  umc-master/src/components/SearchBar/SearchSection.tsx
  umc-master/src/pages/main/MainPage.tsx
  umc-master/src/pages/main/components/Banner.tsx
  umc-master/src/pages/main/components/Categories.tsx
  umc-master/src/pages/main/components/QuizBox.tsx
  umc-master/src/pages/main/components/TipsSection.tsx
  umc-master/vercel.json
  umc-master/yarn.lock
Labels: 🎨 UI

#14 Feat/#10 UI login page
  umc-master/package-lock.json
  umc-master/package.json
  umc-master/src/assets/kakao_login/kakao_login_large_wide.png
  umc-master/src/assets/kakao_login/kakao_login_medium_wide.png
  umc-master/src/components/Button/Button.tsx
  umc-master/src/components/Input/Input.tsx
  umc-master/src/pages/auth/LoginPage.tsx
  umc-master/src/pages/auth/Login_components/ButtonBox.tsx
  umc-master/src/pages/auth/Login_components/InputForm.tsx
  umc-master/src/pages/auth/Login_components/Title.tsx
  umc-master/yarn.lock
Labels: 🎨 UI

#17 Feat/#16 UI my page
  umc-master/src/components/InterestTag/InterestTag.tsx
  umc-master/src/pages/mypage/MyPage.tsx
  umc-master/src/pages/mypage/components/BestInterest.tsx
  umc-master/src/pages/mypage/components/ProfileSection.tsx
  umc-master/src/pages/mypage/components/RecentTips.tsx
  umc-master/src/pages/mypage/components/Section.tsx
  umc-master/src/pages/mypage/components/TipCard.tsx
  umc-master/src/pages/mypage/dummyData/dummyData.ts
  umc-master/src/router/routePaths.ts
  umc-master/src/router/routes.tsx
Labels: 🎨 UI

#18 Feat/#12 UI landing page
  umc-master/.eslintrc.json
  umc-master/package.json
  umc-master/src/assets/gift.png
  umc-master/src/assets/logo.png
  umc-master/src/assets/trophy.png
  umc-master/src/components/Footer/Footer.tsx
  umc-master/src/components/NavigationBar/NavigationBar.tsx
  umc-master/src/hooks/index.ts
  umc-master/src/hooks/useScrollAnimation.ts
  umc-master/src/index.css
  umc-master/src/layouts/index.ts
  umc-master/src/layouts/root-layout.tsx
  umc-master/src/pages/landing/LandingPage.tsx
  umc-master/src/pages/landing/components/InfluencerSection.tsx
  umc-master/src/pages/landing/components/SavedTipsSection.tsx
  umc-master/src/pages/landing/components/SectionScrollIndicator.tsx
  umc-master/src/pages/landing/components/TipsSection.tsx
  umc-master/src/pages/landing/components/TitleSection.tsx
  umc-master/src/router/routes.tsx
  umc-master/yarn.lock
Labels: 🎨 UI

#23 Chore/#22 design system
  umc-master/index.html
  umc-master/src/App.tsx
  umc-master/src/components/common/index.ts
  umc-master/src/components/common/typography.ts
  umc-master/src/styles/globalStyle.ts
  umc-master/src/styles/index.ts
  umc-master/src/styles/theme.ts
Labels: ⚙ chore

#27 Chore/#22 추가된 디자인 시스템 반영
  umc-master/src/components/common/typography.ts
  umc-master/src/styles/theme.ts
Labels: ⚙ chore

#32 Feat/#24 MainPage / SearchPage Design Modify & Design System 추가
  umc-master/src/components/Card/BigCard.tsx
  umc-master/src/components/Card/Card.tsx
  umc-master/src/components/SearchBar/SearchSection.tsx
  umc-master/src/components/SearchBar/components/SearchTitle.tsx
  umc-master/src/components/Tag/Tag.tsx
  umc-master/src/components/common/typography.ts
  umc-master/src/pages/landing/components/SavedTipsSection.tsx
  umc-master/src/pages/main/MainPage.tsx
  umc-master/src/pages/main/components/Banner.tsx
  umc-master/src/pages/main/components/Categories.tsx
  umc-master/src/pages/main/components/QuizBox.tsx
  umc-master/src/pages/main/components/TipsSection.tsx
  umc-master/src/pages/search/SearchPage.tsx
  umc-master/src/pages/search/components/RecommendTipsSection.tsx
  umc-master/src/styles/theme.ts
Labels: 🎨 UI

#31 Feat/#25 네비게이션바, 푸터 및 svg관련 설정
  umc-master/package.json
  umc-master/src/assets/icons/alarm.svg
  umc-master/src/assets/icons/close.svg
  umc-master/src/assets/logo-icon.png
  umc-master/src/assets/logo.png
  umc-master/src/components/Footer/Footer.tsx
  umc-master/src/components/Modal/alarm.tsx
  umc-master/src/components/NavigationBar/NavigationBar.tsx
  umc-master/src/layouts/root-layout.tsx
  umc-master/src/vite-env.d.ts
  umc-master/svg.d.ts
  umc-master/tsconfig.app.json
  umc-master/tsconfig.json
  umc-master/tsconfig.node.json
  umc-master/vite-env.d.ts
  umc-master/vite.config.ts
  umc-master/yarn.lock
Labels: 🎨 UI

#37 Feat/#33 UI community page UI & CreateAndPostPage UI
  umc-master/package.json
  umc-master/src/assets/icons/plus.svg
  umc-master/src/components/Modal/search.tsx
  umc-master/src/components/SearchBar/SearchSection.tsx
  umc-master/src/components/SearchBar/components/ModalSearchBar.tsx
  umc-master/src/components/Tag/Tag.tsx
  umc-master/src/pages/community/CommunityPage.tsx
  umc-master/src/pages/community/components/Banner.tsx
  umc-master/src/pages/createPost/CreatePostPage.tsx
  umc-master/src/pages/createPost/components/ImageUpload.tsx
  umc-master/src/pages/createPost/components/Title.tsx
  umc-master/src/pages/main/components/Categories.tsx
  umc-master/src/pages/main/components/CategoriesInputSection.tsx
  umc-master/src/pages/main/components/TipsSection.tsx
Labels: 🎨 UI

#35 Feat/#34 UI login error message
  umc-master/package.json
  umc-master/src/components/Button/Button.tsx
  umc-master/src/components/Input/Input.tsx
  umc-master/src/hooks/useInput.ts
  umc-master/src/pages/auth/LoginPage.tsx
  umc-master/src/pages/auth/Login_components/ButtonBox.tsx
  umc-master/src/pages/auth/Login_components/InputForm.tsx
  umc-master/src/utils/validation.ts
  umc-master/yarn.lock
Labels: ✨feature, 🎨 UI

#40 Feat/#38 pagination 구현 & Skeleton UI TipSection
  umc-master/.gitignore
  umc-master/package.json
  umc-master/src/apis/axios-instance.ts
  umc-master/src/assets/dummy/dummyData.ts
  umc-master/src/components/Card/BigCard.tsx
  umc-master/src/components/Skeleton/SkeletonBigCard.tsx
  umc-master/src/components/Skeleton/SkeletonCard.tsx
  umc-master/src/hooks/queries/useGetTips.ts
  umc-master/src/hooks/usePagination.ts
  umc-master/src/main.tsx
  umc-master/src/pages/community/CommunityPage.tsx
  umc-master/src/pages/main/MainPage.tsx
  umc-master/src/pages/main/components/CategoriesInputSection.tsx
  umc-master/src/pages/main/components/TipsSection.tsx
  umc-master/src/pages/search/SearchPage.tsx
  umc-master/src/pages/search/components/RecommendTipsSection.tsx
  umc-master/yarn.lock
Labels: ✨feature, 🎨 UI

#39 Feat/#29 UI my page modify
  umc-master/src/assets/Dropdown Arrow.svg
  umc-master/src/assets/close.svg
  umc-master/src/assets/icons/cameraImg.svg
  umc-master/src/components/Button/Button.tsx
  umc-master/src/components/InterestTag/InterestTag.tsx
  umc-master/src/components/Tag/Tag.tsx
  umc-master/src/pages/mypage/MyPage.tsx
  umc-master/src/pages/mypage/components/BestInterest.tsx
  umc-master/src/pages/mypage/components/ProfileSection.tsx
  umc-master/src/pages/mypage/components/RecentTips.tsx
  umc-master/src/pages/mypage/components/Section.tsx
  umc-master/src/pages/mypage/components/TipCard.tsx
  umc-master/src/pages/mypage/dummyData/dummyData.ts
  umc-master/src/pages/mypage/dummyData/image.png
  umc-master/src/pages/mypage/dummyData/region_dummy.ts
  umc-master/src/pages/mypage/modal/InterestEditModal.tsx
  umc-master/src/pages/mypage/modal/ProfileEditModal.tsx
Labels: 🎨 UI

#42 Feat/#21 UI signup page
  umc-master/src/assets/add.svg
  umc-master/src/assets/cameraImg.svg
  umc-master/src/assets/profile_null.png
  umc-master/src/assets/remove.svg
  umc-master/src/components/Button/Button.tsx
  umc-master/src/pages/auth/SignUpPage.tsx
  umc-master/src/pages/auth/Signup_components/AgreementForm.tsx
  umc-master/src/pages/auth/Signup_components/EmailForm.tsx
  umc-master/src/pages/auth/Signup_components/InterestForm.tsx
  umc-master/src/pages/auth/Signup_components/PasswordForm.tsx
  umc-master/src/pages/auth/Signup_components/PrivacyForm.tsx
  umc-master/src/pages/auth/Signup_components/SignupState.tsx
  umc-master/src/pages/auth/dummydata/region_dummy.ts
Labels: 🎨 UI

#47 Feat/#46 feat quiz banner
  umc-master/package.json
  umc-master/src/assets/dummy/dummyCategories.ts
  umc-master/src/assets/dummyCat.jpg
  umc-master/src/assets/icons/search.svg
  umc-master/src/assets/icons/x.svg
  umc-master/src/assets/mainCharacter.png
  umc-master/src/components/Modal/compelete.tsx
  umc-master/src/components/SearchBar/components/SearchBar.tsx
  umc-master/src/pages/community/CommunityPage.tsx
  umc-master/src/pages/createPost/CreatePostPage.tsx
  umc-master/src/pages/main/MainPage.tsx
  umc-master/src/pages/main/components/QuizBox.tsx
  umc-master/src/store/modalStore.ts
  umc-master/src/store/quizStore.ts
  umc-master/yarn.lock
Labels: ✨feature
